### ISSUE TITLE
Video Calling Issue

### ISSUE THREAD

**Issue by NetDevM** [IEvangelist/Blazing.Twilio.Video#2]
Hi,
I have deployed this app in azure 
https://blazingwasmvideoserver20210331131036.azurewebsites.net/#

but it's not working as expected.

scenario
user 1-> created a room
user 2-> connected in a room
user 2-> when leaves room and rejoins ( i did it for 2-3 times, and the app stucked no remote user video was displayed)

**Comment by IEvangelist** [comment]
Hi @RahulSapkota - thank you for posting this issue, however; this app was intended for demonstration purposes and notably is **_not_** production ready. That seems like a rather specific use case. I just tested it, on your Azure instance and it worked for me. You might want to consider some additional logging, and debugging.
