### ISSUE TITLE
Serverless?

### ISSUE THREAD

**Issue by dcuccia** [IEvangelist/Blazing.Twilio.Video#3]
@IEvangelist,

Thank you for putting together this great demo. After reviewing the code briefly, it seems the server project's only two roles are to:

1) provide a REST endpoint for Twilio rooms & room details
2) provide a SignalR hub for broadcasting room changes

If I wanted to modify to a more "serverless" approach, presumably 1) and 2) could easily be handled by Azure functions and Azure SignalR service, respectively. Or, if publishing updates wasn't a requirement, remove 2) altogether.

Does that sound right? Any issues you can foresee with this approach?

David

**Comment by IEvangelist** [comment]
Hi @dcuccia - I have thought about making this serverless already. It is absolutely doable, and both of your suggestions are a step in the right direction. I'd love to see how you go about implementing this, if you fork my repo and add it perhaps we could merge that back here when you're done?
